# -*- coding: utf-8 -*-
"""FOOD CASTING.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-vLcBJFEDtFn4eBAwJ5n-ytBRC0BarOw
"""

import os

os.environ["KAGGLE_USERNAME"] = "kayalmass"
os.environ["KAGGLE_KEY"] = "0a056c2af71cce7989103f6e9b7948e9"

!pip install kaggle

!kaggle datasets download -d kannanaikkal/food-demand-forecasting

!unzip food-demand-forecasting.zip -d fooddemand

import os

print(os.listdir('/content'))
print(os.listdir('/content/fooddemand'))

import pandas as pd

train = pd.read_csv('/content/fooddemand/train.csv')
meal = pd.read_csv('/content/fooddemand/meal_info.csv')
center = pd.read_csv('/content/fooddemand/fulfilment_center_info.csv')

print(train.shape)
print(train.head())

df = train.merge(meal, on='meal_id', how='left')
df = df.merge(center, on='center_id', how='left')

print(df.shape)
print(df.head())

print(df.columns)

print(df.isnull().sum())

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in ['category', 'cuisine', 'center_type']:
    df[col] = le.fit_transform(df[col])

print(df.head())

X = df.drop('num_orders', axis=1)
y = df['num_orders']

print(X.shape)
print(y.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

print("Model Training Completed!")

y_pred = model.predict(X_test)

print(y_pred[:10])

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("MAE :", mean_absolute_error(y_test, y_pred))
print("MSE :", mean_squared_error(y_test, y_pred))
print("R2 Score :", r2_score(y_test, y_pred))

import pandas as pd
import matplotlib.pyplot as plt

importance = model.feature_importances_

feature_imp = pd.DataFrame({
    'Feature': X.columns,
    'Importance': importance
})

feature_imp = feature_imp.sort_values(
    by='Importance',
    ascending=False
)

print(feature_imp.head(10))

plt.figure(figsize=(10,5))
plt.bar(feature_imp['Feature'][:10],
        feature_imp['Importance'][:10])
plt.xticks(rotation=45)
plt.title("Top 10 Important Features")
plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))
plt.scatter(y_test, y_pred)
plt.xlabel("Actual Orders")
plt.ylabel("Predicted Orders")
plt.title("Actual vs Predicted Orders")
plt.show()

import joblib

joblib.dump(model, 'food_demand_model.pkl')

print("Model Saved Successfully")

from sklearn.linear_model import LinearRegression

lr_model = LinearRegression()

lr_model.fit(X_train, y_train)

print("Linear Regression Model Trained Successfully!")

y_pred_lr = lr_model.predict(X_test)

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("MAE :", mean_absolute_error(y_test, y_pred_lr))
print("MSE :", mean_squared_error(y_test, y_pred_lr))
print("R2 Score :", r2_score(y_test, y_pred_lr))

from sklearn.metrics import mean_squared_error
import numpy as np

rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("RMSE :", rmse)

from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
accuracy = r2 * 100

print("Accuracy :", accuracy, "%")

