# -*- coding: utf-8 -*-
"""machine learning beg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12H6akS9LiOOi-aPl1INKvBKvSBgZOZSU

import pandas as pd

def load_csv(file_path):
    df = pd.read_csv(file_path)

    # Remove extra spaces from column names
    df.columns = df.columns.str.strip()

    return df

def get_shape(df):
    return df.shape

def get_column_names(df):
    return df.columns.tolist()

def get_data_types(df):
    return df.dtypes

def get_missing_values(df):
    return df.isnull().sum()

def get_summary(df):
    return df.describe()

# Main Program
if __name__ == "__main__":
    file_path = "loan_approval_dataset.csv"

    df = load_csv(file_path)

    print("Shape of the dataset:")
    print(get_shape(df))

    print("\nColumn names:")
    print(get_column_names(df))

    print("\nData types:")
    print(get_data_types(df))

    print("\nMissing values:")
    print(get_missing_values(df))

    print("\nSummary statistics:")
    print(get_summary(df))

output:
chef@0790aa9bfe8e:~/workspace$ ./venv/bin/python3 model.py
Shape of the dataset:
(4269, 13)

Column names:
['loan_id', 'no_of_dependents', 'education', 'self_employed', 'income_annum', 'loan_amount', 'loan_term', 'cibil_score', 'residential_assets_value', 'commercial_assets_value', 'luxury_assets_value', 'bank_asset_value', 'loan_status']

Data types:
loan_id                     int64
no_of_dependents            int64
education                     str
self_employed                 str
income_annum                int64
loan_amount                 int64
loan_term                   int64
cibil_score                 int64
residential_assets_value    int64
commercial_assets_value     int64
luxury_assets_value         int64
bank_asset_value            int64
loan_status                   str
dtype: object

Missing values:
loan_id                     0
no_of_dependents            0
education                   0
self_employed               0
income_annum                0
loan_amount                 0
loan_term                   0
cibil_score                 0
residential_assets_value    0
commercial_assets_value     0
luxury_assets_value         0
bank_asset_value            0
loan_status                 0
dtype: int64

Summary statistics:
           loan_id  no_of_dependents  ...  luxury_assets_value  bank_asset_value
count  4269.000000       4269.000000  ...         4.269000e+03      4.269000e+03
mean   2135.000000          2.498712  ...         1.512631e+07      4.976692e+06
std    1232.498479          1.695910  ...         9.103754e+06      3.250185e+06
min       1.000000          0.000000  ...         3.000000e+05      0.000000e+00
25%    1068.000000          1.000000  ...         7.500000e+06      2.300000e+06
50%    2135.000000          3.000000  ...         1.460000e+07      4.600000e+06
75%    3202.000000          4.000000  ...         2.170000e+07      7.100000e+06
max    4269.000000          5.000000  ...         3.920000e+07      1.470000e+07

[8 rows x 10 columns]


# Preprocessing Dataset - Loan Approval

import pandas as pd
import warnings
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split

warnings.filterwarnings("ignore", category=Warning)

def load_csv(file_path):
    df = pd.read_csv(file_path)
    return df

def get_column_types(df):
    numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
    categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
    return numerical_cols, categorical_cols

def impute_missing_values(df, numerical_cols, categorical_cols):
    num_imputer = SimpleImputer(strategy='mean')
    cat_imputer = SimpleImputer(strategy='most_frequent')

    df[numerical_cols] = num_imputer.fit_transform(df[numerical_cols])
    df[categorical_cols] = cat_imputer.fit_transform(df[categorical_cols])

    return df

def encode_categorical(df, categorical_cols):
    le = LabelEncoder()

    for col in categorical_cols:
        df[col] = le.fit_transform(df[col])

    return df

def scale_numerical(df, numerical_cols):
    scaler = MinMaxScaler()

    df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

    return df

def split_data(df):
    y = df['loan_status']

    X = df.drop(['loan_id', 'loan_status'], axis=1)

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.2,
        random_state=42
    )

    return X_train, X_test, y_train, y_test

# --- Main Execution ---
if __name__ == '__main__':
    file_path = 'loan_approval_dataset.csv'

    df = load_csv(file_path)

    numerical_cols, categorical_cols = get_column_types(df)
    print("Numerical Columns:", numerical_cols)
    print("Categorical Columns:", categorical_cols)
    print()

    df = impute_missing_values(df, numerical_cols, categorical_cols)

    print("Encode categorical variables")
    df = encode_categorical(df, categorical_cols)
    print(df.head(5))

    print("Scale numerical features")
    df = scale_numerical(df, numerical_cols)
    print(df.head(5))

    print("Split dataset into training and testing sets")
    X_train, X_test, y_train, y_test = split_data(df)

    print("X_train shape:", X_train.shape)
    print("X_test shape:", X_test.shape)

output:
chef@a426a4ebf8fb:~/workspace$ ./venv/bin/python3 data_cleaner.py
Numerical Columns: ['loan_id', 'no_of_dependents', 'income_annum', 'loan_amount', 'loan_term', 'cibil_score', 'residential_assets_value', 'commercial_assets_value', 'luxury_assets_value', 'bank_asset_value']
Categorical Columns: ['education', 'self_employed', 'loan_status']

Encode categorical variables
   loan_id  no_of_dependents  education  ...  luxury_assets_value  bank_asset_value  loan_status
0      1.0               2.0          0  ...           22700000.0         8000000.0            0
1      2.0               0.0          1  ...            8800000.0         3300000.0            1
2      3.0               3.0          0  ...           33300000.0        12800000.0            1
3      4.0               3.0          0  ...           23300000.0         7900000.0            1
4      5.0               5.0          1  ...           29400000.0         5000000.0            1

[5 rows x 13 columns]
Scale numerical features
    loan_id  no_of_dependents  education  ...  luxury_assets_value  bank_asset_value  loan_status
0  0.000000               0.4          0  ...             0.575835          0.544218            0
1  0.000234               0.0          1  ...             0.218509          0.224490            1
2  0.000469               0.6          0  ...             0.848329          0.870748            1
3  0.000703               0.6          0  ...             0.591260          0.537415            1
4  0.000937               1.0          1  ...             0.748072          0.340136            1

[5 rows x 13 columns]
Split dataset into training and testing sets
X_train shape: (3415, 11)
X_test shape: (854, 11)

# Train Logistic Regression Model - Loan Approval

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

def train_logistic_regression(X_train, y_train):
    model = LogisticRegression(max_iter=1000)
    model.fit(X_train, y_train)
    return model

def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)
    report = classification_report(y_test, y_pred)

    metrics = {
        "accuracy": accuracy,
        "confusion_matrix": cm,
        "classification_report": report
    }

    return metrics

def predict_loan_approval(new_applicant, model):
    df_input = pd.DataFrame([new_applicant])
    prediction = model.predict(df_input)[0]

    return "Approved" if prediction == 1 else "Not Approved"


# --- Main Execution ---
if __name__ == '__main__':
    from sklearn.model_selection import train_test_split
    from sklearn.preprocessing import LabelEncoder, MinMaxScaler
    from sklearn.impute import SimpleImputer

    df = pd.read_csv('loan_approval_dataset.csv')

    numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
    categorical_cols = df.select_dtypes(include=['object']).columns.tolist()

    # Missing values
    df[numerical_cols] = SimpleImputer(strategy='mean').fit_transform(df[numerical_cols])
    df[categorical_cols] = SimpleImputer(strategy='most_frequent').fit_transform(df[categorical_cols])

    # Encoding
    le = LabelEncoder()
    for col in categorical_cols:
        df[col] = le.fit_transform(df[col])

    # Scaling
    df[numerical_cols] = MinMaxScaler().fit_transform(df[numerical_cols])

    # Split
    y = df['loan_status']
    X = df.drop(columns=['loan_id', 'loan_status'])

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    # Train
    model = train_logistic_regression(X_train, y_train)

    # Evaluate
    print("Target distribution:\n", y.value_counts())
    results = evaluate_model(model, X_test, y_test)

    print("Accuracy:", results['accuracy'])
    print("\nConfusion Matrix:\n", results['confusion_matrix'])
    print("\nClassification Report:\n", results['classification_report'])

    # Predict new applicant
    new_applicant = {
        'no_of_dependents': 2,
        'education': 1,
        'self_employed': 1,
        'income_annum': 40000000,
        'loan_amount': 3000000,
        'loan_term': 15,
        'cibil_score': 700,
        'residential_assets_value': 6000000,
        'commercial_assets_value': 6000000,
        'luxury_assets_value': 75000000,
        'bank_asset_value': 4500000
    }

    result = predict_loan_approval(new_applicant, model)
    print("Loan Status:", result)

output:
Target distribution:
 loan_status
0    2656
1    1613
Name: count, dtype: int64
Accuracy: 0.9121779859484778

Confusion Matrix:
 [[501  35]
 [ 40 278]]

Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.93      0.93       536
           1       0.89      0.87      0.88       318

    accuracy                           0.91       854
   macro avg       0.91      0.90      0.91       854
weighted avg       0.91      0.91      0.91       854

Loan Status: Approved

# Bangalore House Price Prediction Project

location_data = {
    'Whitefield': {
        'base_price': 30,
        'price_per_bhk': 25
    },
    'Sarjapur Road': {
        'base_price': 45,
        'price_per_bhk': 30
    },
    'Electronic City': {
        'base_price': 25,
        'price_per_bhk': 20
    }
}

def calculate_price(location, bhk):

    # Check if location exists
    if location in location_data:

        # Get location details
        data = location_data[location]

        base_price = data['base_price']
        price_per_bhk = data['price_per_bhk']

        # Apply formula
        total_price = base_price + (bhk * price_per_bhk)

        return f"The calculated price for a {bhk} BHK in {location} is {total_price} Lakhs."

    else:
        return f"Sorry, we do not have pricing data for the location '{location}'."

if __name__ == "__main__":
    price1 = calculate_price('Whitefield', 2)
    print(price1)

    price2 = calculate_price('Electronic City', 3)
    print(price2)

    price3 = calculate_price('Sarjapur Road', 3)
    print(price3)

output:
The calculated price for a 2 BHK in Whitefield is 80 Lakhs.
The calculated price for a 3 BHK in Electronic City is 85 Lakhs.
The calculated price for a 3 BHK in Sarjapur Road is 135 Lakhs.

# Clean the Bangalore House Price Dataset

import pandas as pd
import numpy as np

# -------------------------------
# Convert sqft function
# -------------------------------
def convert_sqft_to_num(x):
    if isinstance(x, str):
        tokens = x.split('-')

        if len(tokens) == 2:
            try:
                return (float(tokens[0]) + float(tokens[1])) / 2
            except:
                return None

        try:
            return float(x)
        except:
            return None

    try:
        return float(x)
    except:
        return None


# -------------------------------
# MAIN
# -------------------------------
if __name__ == "__main__":

    df = pd.read_csv("Bengaluru_House_Data.csv")

    # 1. Drop unnecessary columns
    df_cleaned = df.drop(
        ['area_type', 'society', 'balcony', 'availability'],
        axis=1
    )

    # 2. Drop missing values
    df_cleaned = df_cleaned.dropna()

    # 3. Create bhk column
    df_cleaned['bhk'] = df_cleaned['size'].apply(lambda x: int(str(x).split(' ')[0]))

    # 4. Convert total_sqft
    df_cleaned['total_sqft'] = df_cleaned['total_sqft'].apply(convert_sqft_to_num)

    # 5. Drop nulls again
    df_cleaned = df_cleaned.dropna()

    # 6. 🔥 IMPORTANT FIX: remove 'size' column
    df_cleaned = df_cleaned.drop(['size'], axis=1)

    # 7. Save file
    df_cleaned.to_csv("cleaned_bengaluru_house_data.csv", index=False)

    print("Cleaned data saved successfully!")
    print(df_cleaned.head())

output:
                   location  total_sqft  bath   price  bhk
0  Electronic City Phase II      1056.0   2.0   39.07    2
1          Chikka Tirupathi      2600.0   5.0  120.00    4
2               Uttarahalli      1440.0   2.0   62.00    3
3        Lingadheeranahalli      1521.0   3.0   95.00    3
4                  Kothanur      1200.0   2.0   51.00    2

# Build the Complete House Price Prediction Web App

main.py

from flask import Flask, request, render_template
import pickle
import json
import numpy as np
import os

app = Flask(__name__)

__model = None
__data_columns = None
__locations = None

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))

def load_saved_artifacts():
    global __data_columns
    global __locations
    global __model

    print("Loading saved artifacts...")

    with open(os.path.join(PROJECT_ROOT, "columns.json"), "r") as f:
        data = json.load(f)
        __data_columns = data["data_columns"]
        __locations = __data_columns[3:]

    with open(os.path.join(PROJECT_ROOT, "bangalore_house_price_model.pickle"), "rb") as f:
        __model = pickle.load(f)

    print("Loading done")

load_saved_artifacts()

def get_estimated_price(location, sqft, bhk, bath):
    try:
        loc_index = __data_columns.index(location.lower())
    except:
        loc_index = -1

    x = np.zeros(len(__data_columns))
    x[0] = sqft
    x[1] = bath
    x[2] = bhk

    if loc_index >= 0:
        x[loc_index] = 1

    return round(__model.predict([x])[0], 2)

@app.route('/')
def home():
    return render_template('index.html', locations=__locations)

@app.route('/predict', methods=['POST'])
def predict():

    print("Form Data:", request.form)

    total_sqft = float(
        request.form.get('sqft') or
        request.form.get('total_sqft') or
        0
    )

    location = request.form.get('location')

    bhk = int(
        request.form.get('bhk') or
        0
    )

    bath = int(
        request.form.get('bath') or
        0
    )

    estimated_price = get_estimated_price(
        location,
        total_sqft,
        bhk,
        bath
    )

    return render_template(
        'index.html',
        prediction_text=f'Estimated Price: {estimated_price} Lakhs',
        locations=__locations
    )

if __name__ == "__main__":
    print("Starting Flask Server...")
    app.run(host='0.0.0.0', port=3000, debug=True)

model.py

import pandas as pd
import numpy as np
import pickle
import json

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# ---------------- Load data ----------------
df = pd.read_csv("cleaned_bengaluru_house_data.csv")

# ---------------- Handle location ----------------
df.location = df.location.apply(lambda x: x.strip())

locations = df['location'].value_counts()
df.location = df.location.apply(lambda x: x if locations[x] >= 10 else 'other')

# ---------------- One hot encoding ----------------
dummies = pd.get_dummies(df.location)
df = pd.concat([df, dummies.drop('other', axis=1)], axis=1)
df = df.drop('location', axis=1)

# ---------------- Outlier removal ----------------
df['price_per_sqft'] = df['price'] * 100000 / df['total_sqft']

df = df[df['total_sqft'] / df['bhk'] >= 300]

df = df.drop('price_per_sqft', axis=1)

# ---------------- Features & target ----------------
X = df.drop('price', axis=1)
y = df['price']

# ---------------- Train model ----------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=10
)

model = LinearRegression()
model.fit(X_train, y_train)

# ---------------- Save model ----------------
with open("bangalore_house_price_model.pickle", "wb") as f:
    pickle.dump(model, f)

# ---------------- Save columns ----------------
columns = {
    "data_columns": list(X.columns)
}

with open("columns.json", "w") as f:
    json.dump(columns, f)

print("Model training completed and saved!")

output:
chef@5cc80f6d54a9:~/workspace$ ./venv/bin/python3 model.py && ./venv/bin/python3 main.py
Model training completed and saved!
Loading saved artifacts...
Loading done
Starting Flask Server...
 * Serving Flask app 'main'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:3000
 * Running on http://172.17.0.4:3000
Press CTRL+C to quit
 * Restarting with stat
Loading saved artifacts...
Loading done
Starting Flask Server...
 * Debugger is active!
 * Debugger PIN: 929-581-151
172.17.0.2 - - [10/Jun/2026 10:39:17] "HEAD / HTTP/1.1" 200 -
172.17.0.2 - - [10/Jun/2026 10:39:17] "HEAD / HTTP/1.1" 200 -
172.17.0.2 - - [10/Jun/2026 10:39:18] "GET / HTTP/1.1" 200 -
Form Data: ImmutableMultiDict([('total_sqft', '1200'), ('bhk', '2'), ('bath', '2'), ('location', '1st Block Jayanagar')])
/home/chef/workspace/venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
172.17.0.2 - - [10/Jun/2026 10:39:36] "POST /predict HTTP/1.1" 200 -

Estimated Price: 91.66 Lakhs

# Calculate F-Score for Evaluating Binary Classifier

import numpy as np

def f_score(y_true, y_pred, beta):
    '''
    Calculate F-Score for a binary classification task.

    Args:
        y_true (np.ndarray): True binary labels.
        y_pred (np.ndarray): Predicted binary labels.
        beta (float): Weight factor for recall.

    Returns:
        float: F-Score rounded to 3 decimal places.
    '''

    # Count True Positives (TP)
    TP = np.sum((y_true == 1) & (y_pred == 1))

    # Count False Positives (FP)
    FP = np.sum((y_true == 0) & (y_pred == 1))

    # Count False Negatives (FN)
    FN = np.sum((y_true == 1) & (y_pred == 0))

    # Avoid division by zero
    if TP + FP == 0:
        precision = 0
    else:
        precision = TP / (TP + FP)

    if TP + FN == 0:
        recall = 0
    else:
        recall = TP / (TP + FN)

    # Avoid division by zero in F-score formula
    if (beta**2 * precision + recall) == 0:
        return 0.0

    # Calculate F-Score
    f_beta = ((1 + beta**2) * precision * recall) / ((beta**2 * precision) + recall)

    return round(f_beta, 3)


# --- Main Execution Block ---
if __name__ == '__main__':
    y_true = np.array([0, 1, 0, 1, 1, 0, 1, 0])
    y_pred = np.array([0, 1, 1, 1, 0, 0, 1, 1])
    beta = 1

    result = f_score(y_true, y_pred, beta)
    print("F-Score:", result)  # Expected: 0.667

output:
F-Score: 0.667

# Implement K-Fold Cross-Validation

import numpy as np

def k_fold_cross_validation(X: np.ndarray, y: np.ndarray, k=5, shuffle=True):
    '''
    Perform custom k-fold cross-validation split without using sklearn.

    Parameters:
        X (np.ndarray): Feature array.
        y (np.ndarray): Target/label array.
        k (int): Number of folds.
        shuffle (bool): Whether to shuffle the data before splitting.

    Returns:
        List[Tuple[List[int], List[int]]]: Each tuple contains (train_indices, test_indices).
    '''

    # Get number of samples
    n_samples = len(X)

    # Create indices
    indices = np.arange(n_samples)

    # Shuffle if required
    if shuffle:
        np.random.shuffle(indices)

    # Calculate fold sizes
    fold_sizes = np.full(k, n_samples // k, dtype=int)
    fold_sizes[:n_samples % k] += 1

    splits = []
    current = 0

    for fold_size in fold_sizes:
        start, stop = current, current + fold_size

        # Test indices for current fold
        test_indices = indices[start:stop]

        # Remaining indices are training indices
        train_indices = np.concatenate(
            (indices[:start], indices[stop:])
        )

        splits.append(
            (train_indices.tolist(), test_indices.tolist())
        )

        current = stop

    return splits


# --- Main Execution Block ---
if __name__ == '__main__':
    X = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
    y = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

    splits = k_fold_cross_validation(X, y, k=5, shuffle=False)

    for i, (train_idx, test_idx) in enumerate(splits):
        print(f"Fold {i + 1}:")
        print("Train indices:", train_idx)
        print("Test indices:", test_idx)
        print()

output:
Fold 1:
Train indices: [2, 3, 4, 5, 6, 7, 8, 9]
Test indices: [0, 1]

Fold 2:
Train indices: [0, 1, 4, 5, 6, 7, 8, 9]
Test indices: [2, 3]

Fold 3:
Train indices: [0, 1, 2, 3, 6, 7, 8, 9]
Test indices: [4, 5]

Fold 4:
Train indices: [0, 1, 2, 3, 4, 5, 8, 9]
Test indices: [6, 7]

Fold 5:
Train indices: [0, 1, 2, 3, 4, 5, 6, 7]
Test indices: [8, 9]

# Logistic Regression Model Using Gradient Descent

import numpy as np

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def train_logreg(X, y, learning_rate=0.01, epochs=20):
    '''
    Train Logistic Regression using Gradient Descent.

    Parameters:
        X (np.ndarray): Input features
        y (np.ndarray): Binary labels
        learning_rate (float): Learning rate
        epochs (int): Number of training iterations

    Returns:
        tuple: (weights, losses)
    '''

output:
[np.float64(-0.0003), np.float64(0.4038), np.float64(0.3379)]
[np.float64(2.7726), np.float64(2.6485), np.float64(2.533), np.float64(2.4254), np.float64(2.325), np.float64(2.2314), np.float64(2.1441), np.float64(2.0625), np.float64(1.9862), np.float64(1.9148), np.float64(1.8479), np.float64(1.7852), np.float64(1.7263), np.float64(1.6708), np.float64(1.6187), np.float64(1.5696), np.float64(1.5232), np.float64(1.4794), np.float64(1.438), np.float64(1.3988)]

# Email Spam Classifier

import string

corpus = [
    'URGENT! You have won a 1 week FREE membership in our prize jackpot.',
    'Hey, what time is the meeting tomorrow?',
    'WINNER!! As a valued network customer you have been selected to receive a prize.',
    'Are you coming to the party tonight?',
    'Congratulations! You won a free flight to Bahamas.'
]

def build_vocabulary(corpus):
    '''
    Builds a sorted list of unique words from all documents in the corpus.
    '''
    vocab_set = set()

    for doc in corpus:
        cleaned = doc.lower().translate(
            str.maketrans('', '', string.punctuation)
        )
        words = cleaned.split()
        vocab_set.update(words)

    return sorted(list(vocab_set))


def vectorize_text(text, vocabulary):
    '''
    Converts a single text document into a numerical vector.
    '''
    vector = [0] * len(vocabulary)

    cleaned = text.lower().translate(
        str.maketrans('', '', string.punctuation)
    )
    words = cleaned.split()

    for word in words:
        if word in vocabulary:
            idx = vocabulary.index(word)
            vector[idx] += 1

    return vector


# --- Main Execution ---
if __name__ == '__main__':

    vocabulary = build_vocabulary(corpus)

    print(f"Vocabulary ({len(vocabulary)} words):")
    print(vocabulary)
    print("-" * 30)

    print("Vectorized Corpus:")

    for doc in corpus:
        vector = vectorize_text(doc, vocabulary)
        print(f"Original: {doc}")
        print(f"Vector:   {vector}\n")

output:
Vocabulary (36 words):
['1', 'a', 'are', 'as', 'bahamas', 'been', 'coming', 'congratulations', 'customer', 'flight', 'free', 'have', 'hey', 'in', 'is', 'jackpot', 'meeting', 'membership', 'network', 'our', 'party', 'prize', 'receive', 'selected', 'the', 'time', 'to', 'tomorrow', 'tonight', 'urgent', 'valued', 'week', 'what', 'winner', 'won', 'you']
------------------------------
Vectorized Corpus:
Original: URGENT! You have won a 1 week FREE membership in our prize jackpot.
Vector:   [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1]

Original: Hey, what time is the meeting tomorrow?
Vector:   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0]

Original: WINNER!! As a valued network customer you have been selected to receive a prize.
Vector:   [0, 2, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1]

Original: Are you coming to the party tonight?
Vector:   [0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1]

Original: Congratulations! You won a free flight to Bahamas.
Vector:   [0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1]

# Cleaning the Spam Dataset

import pandas as pd

def clean_spam_data(input_file='spam.csv', output_file='spam_cleaned.csv'):
    '''
    Loads, cleans, and saves the spam dataset.
    '''

    # 1. Load dataset
    df = pd.read_csv(input_file, encoding='latin-1')

    # 2. Remove unnecessary columns
    df = df.drop(
        columns=['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'],
        errors='ignore'
    )

    # Rename columns
    df = df.rename(
        columns={
            'v1': 'label',
            'v2': 'message'
        }
    )

    # 3. Convert labels
    df['label'] = df['label'].map({
        'ham': 0,
        'spam': 1
    })

    # 4. Drop missing messages
    df = df.dropna(subset=['message'])

    # 5. Save cleaned dataset
    df.to_csv(output_file, index=False)

    print(f"--- Successfully cleaned data and saved to {output_file} ---")
    print("Head of the cleaned data:")
    print(df.head())

    return df


# --- Main Execution ---
if __name__ == '__main__':
    clean_spam_data()

output:
--- Successfully cleaned data and saved to spam_cleaned.csv ---
Head of the cleaned data:
   label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

# Email Spam Classifier

main.py

from flask import Flask, render_template, request
import pickle
import os

app = Flask(__name__)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

MODEL_PATH = os.path.join(BASE_DIR, "spam_model.pkl")
VECTORIZER_PATH = os.path.join(BASE_DIR, "vectorizer.pkl")

with open(MODEL_PATH, "rb") as f:
    model = pickle.load(f)

with open(VECTORIZER_PATH, "rb") as f:
    vectorizer = pickle.load(f)

model.py

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
import pickle

print("--- Starting Model Training ---")

# 1. Load cleaned dataset
df = pd.read_csv("spam_cleaned.csv")

# 2. Features and labels
X = df["message"]
y = df["label"]

# 3. Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

# 4. Vectorization
vectorizer = CountVectorizer()

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# 5. Train model
model = MultinomialNB()
model.fit(X_train_vec, y_train)

# 6. Evaluate
y_pred = model.predict(X_test_vec)
accuracy = accuracy_score(y_test, y_pred)

print(f"Model Accuracy: {accuracy * 100:.2f}%")

# 7. Save model and vectorizer
with open("spam_model.pkl", "wb") as f:
    pickle.dump(model, f)

with open("vectorizer.pkl", "wb") as f:
    pickle.dump(vectorizer, f)

print("--- Model and Vectorizer saved successfully! ---")

output:
--- Starting Model Training ---
Model Accuracy: 98.39%
--- Model and Vectorizer saved successfully! ---
 * Serving Flask app 'main'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:3000
 * Running on http://172.17.0.9:3000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 552-617-907
172.17.0.2 - - [10/Jun/2026 10:48:44] "HEAD / HTTP/1.1" 200 -
172.17.0.2 - - [10/Jun/2026 10:48:44] "HEAD / HTTP/1.1" 200 -
172.17.0.2 - - [10/Jun/2026 10:48:44] "GET / HTTP/1.1" 200 -
172.17.0.2 - - [10/Jun/2026 10:49:22] "POST /predict HTTP/1.1" 200 -


# Student Dropout Risk Analysis

import pandas as pd
import numpy as np

def load_data(file_path: str) -> pd.DataFrame:
    '''
    Load the dataset from a CSV file.
    '''
    df = pd.read_csv(file_path)
    return df


def explore_data(df: pd.DataFrame):
    '''
    Perform basic data exploration.
    '''
    print("Dataset Shape:", df.shape)
    print("\nData Types:\n", df.dtypes)
    print("\nMissing Values:\n", df.isnull().sum())

    # Categorical distributions
    categorical_cols = ['Gender', 'Course', 'Tuition fees up to date', 'Debtor']

    for col in categorical_cols:
        if col in df.columns:
            print(f"\n{col} Distribution:\n", df[col].value_counts())


def create_approval_rate(df: pd.DataFrame):
    '''
    approval_rate = approved / enrolled (1st semester)
    '''
    df['approval_rate'] = df['Curricular units 1st sem (approved)'] / \
                           df['Curricular units 1st sem (enrolled)']

    # avoid division issues
    df['approval_rate'] = df['approval_rate'].replace([np.inf, -np.inf], np.nan)

    return df


def create_performance_score(df: pd.DataFrame):
    '''
    performance_score = approved / evaluations (1st semester)
    '''
    df['performance_score'] = df['Curricular units 1st sem (approved)'] / \
                               df['Curricular units 1st sem (evaluations)']

    # avoid division issues
    df['performance_score'] = df['performance_score'].replace([np.inf, -np.inf], np.nan)

    return df


def create_engineered_features(df: pd.DataFrame) -> pd.DataFrame:
    '''
    Create all engineered features.
    '''
    df = create_approval_rate(df)
    df = create_performance_score(df)

    print("\nData with new columns:")
    print(df[['Course', 'Gender', 'approval_rate', 'performance_score']].head())

    return df


# --- Main Execution Block ---
if __name__ == '__main__':
    file_path = 'dataset.csv'

    df = load_data(file_path)

    explore_data(df)

    df = create_engineered_features(df)

output:
Dataset Shape: (4424, 35)

Data Types:
 Marital status                                      int64
Application mode                                    int64
Application order                                   int64
Course                                              int64
Daytime/evening attendance                          int64
Previous qualification                              int64
Nacionality                                         int64
Mother's qualification                              int64
Father's qualification                              int64
Mother's occupation                                 int64
Father's occupation                                 int64
Displaced                                           int64
Educational special needs                           int64
Debtor                                              int64
Tuition fees up to date                             int64
Gender                                              int64
Scholarship holder                                  int64
Age at enrollment                                   int64
International                                       int64
Curricular units 1st sem (credited)                 int64
Curricular units 1st sem (enrolled)                 int64
Curricular units 1st sem (evaluations)              int64
Curricular units 1st sem (approved)                 int64
Curricular units 1st sem (grade)                  float64
Curricular units 1st sem (without evaluations)      int64
Curricular units 2nd sem (credited)                 int64
Curricular units 2nd sem (enrolled)                 int64
Curricular units 2nd sem (evaluations)              int64
Curricular units 2nd sem (approved)                 int64
Curricular units 2nd sem (grade)                  float64
Curricular units 2nd sem (without evaluations)      int64
Unemployment rate                                 float64
Inflation rate                                    float64
GDP                                               float64
Target                                                str
dtype: object

Missing Values:
 Marital status                                    0
Application mode                                  0
Application order                                 0
Course                                            0
Daytime/evening attendance                        0
Previous qualification                            0
Nacionality                                       0
Mother's qualification                            0
Father's qualification                            0
Mother's occupation                               0
Father's occupation                               0
Displaced                                         0
Educational special needs                         0
Debtor                                            0
Tuition fees up to date                           0
Gender                                            0
Scholarship holder                                0
Age at enrollment                                 0
International                                     0
Curricular units 1st sem (credited)               0
Curricular units 1st sem (enrolled)               0
Curricular units 1st sem (evaluations)            0
Curricular units 1st sem (approved)               0
Curricular units 1st sem (grade)                  0
Curricular units 1st sem (without evaluations)    0
Curricular units 2nd sem (credited)               0
Curricular units 2nd sem (enrolled)               0
Curricular units 2nd sem (evaluations)            0
Curricular units 2nd sem (approved)               0
Curricular units 2nd sem (grade)                  0
Curricular units 2nd sem (without evaluations)    0
Unemployment rate                                 0
Inflation rate                                    0
GDP                                               0
Target                                            0
dtype: int64

Gender Distribution:
 Gender
0    2868
1    1556
Name: count, dtype: int64

Course Distribution:
 Course
12    766
9     380
10    355
6     337
15    331
17    268
14    268
11    252
5     226
2     215
3     215
4     210
16    192
7     170
8     141
13     86
1      12
Name: count, dtype: int64

Tuition fees up to date Distribution:
 Tuition fees up to date
1    3896
0     528
Name: count, dtype: int64

Debtor Distribution:
 Debtor
0    3921
1     503
Name: count, dtype: int64

Data with new columns:
   Course  Gender  approval_rate  performance_score
0       2       1            NaN                NaN
1      11       1       1.000000           1.000000
2       5       1       0.000000                NaN
3      15       0       1.000000           0.750000
4       3       0       0.833333           0.555556

# Student Dropout Risk Analysis

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler


# -----------------------------
# 1. Feature Selection
# -----------------------------
def select_features(df: pd.DataFrame) -> pd.DataFrame:
    features = [
        'Age at enrollment',
        'Gender',
        'Debtor',
        'Tuition fees up to date',
        'Curricular units 1st sem (approved)'
    ]
    return df[features]


# -----------------------------
# 2. Missing Values Handling
# -----------------------------
def handle_missing_values(X: pd.DataFrame) -> pd.DataFrame:
    X = X.copy()

    categorical_cols = ['Gender', 'Debtor', 'Tuition fees up to date']
    numerical_cols = ['Age at enrollment', 'Curricular units 1st sem (approved)']

    # categorical
    for col in categorical_cols:
        if X[col].dtype == 'object':
            X[col] = X[col].fillna('Unknown')
        else:
            X[col] = X[col].fillna(X[col].mode()[0])

    # numerical
    for col in numerical_cols:
        X[col] = X[col].fillna(X[col].median())

    return X


# -----------------------------
# 3. Encoding
# -----------------------------
def encode_categorical_features(X: pd.DataFrame) -> pd.DataFrame:
    categorical_cols = ['Gender', 'Debtor', 'Tuition fees up to date']
    return pd.get_dummies(X, columns=categorical_cols, drop_first=True)


# -----------------------------
# 4. Train-Test Split
# -----------------------------
def split_data(X: pd.DataFrame, y: pd.Series, test_size: float = 0.3):
    return train_test_split(
        X, y,
        test_size=test_size,
        random_state=42,
        stratify=y
    )


# -----------------------------
# 5. Decision Tree Model
# -----------------------------
def train_decision_tree(X_train, y_train):
    model = DecisionTreeClassifier(random_state=42)
    model.fit(X_train, y_train)
    return model


# -----------------------------
# 6. Evaluation
# -----------------------------
def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)
    accuracy = model.score(X_test, y_test)
    cm = confusion_matrix(y_test, y_pred)
    return accuracy, cm


# -----------------------------
# 7. L2 Regularization (Ridge)
# -----------------------------
def apply_l2_regularization(X_train, y_train, X_test, y_test):
    scaler = StandardScaler()

    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    reg_model_l2 = LogisticRegression(
        penalty='l2',
        solver='lbfgs',
        max_iter=1000
    )

    reg_model_l2.fit(X_train_scaled, y_train)

    return reg_model_l2


# -----------------------------
# 8. L1 Regularization (Lasso)
# -----------------------------
def apply_l1_regularization(X_train, y_train, X_test, y_test):
    scaler = StandardScaler()

    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    reg_model_l1 = LogisticRegression(
        penalty='l1',
        solver='saga',
        max_iter=1000
    )

    reg_model_l1.fit(X_train_scaled, y_train)

    return reg_model_l1


# -----------------------------
# MAIN
# -----------------------------
if __name__ == '__main__':

    df = pd.read_csv('dataset.csv')

    # Features + preprocessing
    X = select_features(df)
    X = handle_missing_values(X)
    X = encode_categorical_features(X)

    y = df['Target']

    # Split
    X_train, X_test, y_train, y_test = split_data(X, y)

    # Decision Tree
    model = train_decision_tree(X_train, y_train)
    accuracy, cm = evaluate_model(model, X_test, y_test)

    print("\nDecision Tree Model Accuracy:", accuracy)
    print("\nConfusion Matrix:\n", cm)

    # L2 Model
    reg_model_l2 = apply_l2_regularization(X_train, y_train, X_test, y_test)
    acc_l2 = reg_model_l2.score(StandardScaler().fit_transform(X_test), y_test)
    print("\nL2 Regularized Model Accuracy (Ridge):", acc_l2)

    # L1 Model
    reg_model_l1 = apply_l1_regularization(X_train, y_train, X_test, y_test)
    acc_l1 = reg_model_l1.score(StandardScaler().fit_transform(X_test), y_test)
    print("\nL1 Regularized Model Accuracy (Lasso):", acc_l1)

output:
Decision Tree Model Accuracy: 0.6731927710843374

Confusion Matrix:
 [[295  56  76]
 [ 86  52 100]
 [ 53  63 547]]
/home/chef/workspace/venv/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(

L2 Regularized Model Accuracy (Ridge): 0.7048192771084337
/home/chef/workspace/venv/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/chef/workspace/venv/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

L1 Regularized Model Accuracy (Lasso): 0.7048192771084337

# Student Dropout Risk Analysis

import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix


# -----------------------------
# 1. Random Forest
# -----------------------------
def train_random_forest(X_train: pd.DataFrame, y_train: pd.Series):
    rf_model = RandomForestClassifier(
        n_estimators=100,
        random_state=42
    )
    rf_model.fit(X_train, y_train)
    return rf_model


# -----------------------------
# 2. Gradient Boosting
# -----------------------------
def train_gradient_boosting(X_train: pd.DataFrame, y_train: pd.Series):
    gb_model = GradientBoostingClassifier(
        random_state=42
    )
    gb_model.fit(X_train, y_train)
    return gb_model


# -----------------------------
# 3. Cross Validation
# -----------------------------
def apply_k_fold_cross_validation(model, X_train: pd.DataFrame, y_train: pd.Series, cv_splits: int = 5) -> float:
    kf = KFold(n_splits=cv_splits, shuffle=True, random_state=42)

    cv_scores = cross_val_score(
        model,
        X_train,
        y_train,
        cv=kf,
        scoring='accuracy'
    )

    return cv_scores.mean()


# -----------------------------
# 4. Evaluation
# -----------------------------
def evaluate_model(model, X_test: pd.DataFrame, y_test: pd.Series):
    y_pred = model.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    cm = confusion_matrix(y_test, y_pred)

    return accuracy, precision, recall, cm


# -----------------------------
# 5. Feature Selection
# -----------------------------
def select_features(df: pd.DataFrame) -> pd.DataFrame:
    features = [
        'Age at enrollment',
        'Gender',
        'Debtor',
        'Tuition fees up to date',
        'Curricular units 1st sem (approved)'
    ]
    return df[features]


# -----------------------------
# 6. Missing Values
# -----------------------------
def handle_missing_values(X: pd.DataFrame) -> pd.DataFrame:
    X = X.copy()

    categorical_cols = ['Gender', 'Debtor', 'Tuition fees up to date']
    numerical_cols = ['Age at enrollment', 'Curricular units 1st sem (approved)']

    X[categorical_cols] = X[categorical_cols].fillna('Unknown')
    X[numerical_cols] = X[numerical_cols].fillna(X[numerical_cols].median())

    return X


# -----------------------------
# 7. Encoding
# -----------------------------
def encode_categorical_features(X: pd.DataFrame) -> pd.DataFrame:
    categorical_cols = ['Gender', 'Debtor', 'Tuition fees up to date']
    return pd.get_dummies(X, columns=categorical_cols, drop_first=True)


# -----------------------------
# 8. Split Data
# -----------------------------
def split_data(X: pd.DataFrame, y: pd.Series):
    return train_test_split(
        X, y,
        test_size=0.3,
        random_state=42,
        stratify=y
    )


# -----------------------------
# MAIN
# -----------------------------
if __name__ == '__main__':

    df = pd.read_csv('dataset.csv')

    # Pipeline
    X = select_features(df)
    X = handle_missing_values(X)
    X = encode_categorical_features(X)

    y = df['Target']

    X_train, X_test, y_train, y_test = split_data(X, y)

    # ---------------- RANDOM FOREST ----------------
    rf_model = train_random_forest(X_train, y_train)

    rf_cv_score = apply_k_fold_cross_validation(rf_model, X_train, y_train)
    print("Random Forest Cross-validation Accuracy:", rf_cv_score)

    rf_accuracy, rf_precision, rf_recall, rf_cm = evaluate_model(rf_model, X_test, y_test)

    print("\nRandom Forest Model Accuracy:", rf_accuracy)
    print("Random Forest Model Precision:", rf_precision)
    print("Random Forest Model Recall:", rf_recall)
    print("Random Forest Confusion Matrix:\n", rf_cm)


    # ---------------- GRADIENT BOOSTING ----------------
    gb_model = train_gradient_boosting(X_train, y_train)

    gb_cv_score = apply_k_fold_cross_validation(gb_model, X_train, y_train)
    print("\nGradient Boosting Cross-validation Accuracy:", gb_cv_score)

    gb_accuracy, gb_precision, gb_recall, gb_cm = evaluate_model(gb_model, X_test, y_test)

    print("\nGradient Boosting Model Accuracy:", gb_accuracy)
    print("Gradient Boosting Model Precision:", gb_precision)
    print("Gradient Boosting Model Recall:", gb_recall)
    print("Gradient Boosting Confusion Matrix:\n", gb_cm)

output:
Random Forest Cross-validation Accuracy: 0.6763541612382094

Random Forest Model Accuracy: 0.6965361445783133
Random Forest Model Precision: 0.6752063743159149
Random Forest Model Recall: 0.6965361445783133
Random Forest Confusion Matrix:
 [[286  55  86]
 [ 71  61 106]
 [ 35  50 578]]

Gradient Boosting Cross-validation Accuracy: 0.7060732711449267

Gradient Boosting Model Accuracy: 0.7213855421686747
Gradient Boosting Model Precision: 0.6818667821737503
Gradient Boosting Model Recall: 0.7213855421686747
Gradient Boosting Confusion Matrix:
 [[312  41  74]
 [ 85  38 115]
 [ 35  20 608]]
"""