# -*- coding: utf-8 -*-
"""NETFLIX DATASET.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VnggHxfMzmzqGRBRre7ll2PWX4OUPGer
"""

import os

os.environ["KAGGLE_USERNAME"] = "kayalmass"
os.environ["KAGGLE_KEY"] = "0a056c2af71cce7989103f6e9b7948e9"

!pip install kaggle

!kaggle datasets download -d rahulvyasm/netflix-movies-and-tv-shows

!unzip /content/netflix-movies-and-tv-shows.zip -d /content/netflix_dataset

import pandas as pd

df = pd.read_csv(
    '/content/netflix_dataset/netflix_titles.csv',
    encoding='latin1'
)

df.head()

print(df.shape)

print(df.columns)

df.info()

df.head(10)

print(df.isnull().sum())

df.describe()

df.drop(columns=[col for col in df.columns if 'Unnamed' in col], inplace=True)

print(df.columns)

import pandas as pd
df['date_added'] = df['date_added'].astype(str).str.strip()
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')
df['year_added'] = df['date_added'].dt.year
df['month_added'] = df['date_added'].dt.month
df['content_age'] = 2026 - df['release_year']
df[['date_added', 'year_added', 'month_added', 'content_age']].head()

print(df.columns)

df['date_added'].fillna(df['date_added'].mode()[0], inplace=True)

df['release_year'].fillna(df['release_year'].median(), inplace=True)

print(df.head())

df.head()

import matplotlib.pyplot as plt

plt.boxplot(df['release_year'])
plt.title('Outlier Detection using Boxplot (release_year)')
plt.ylabel('Release Year')
plt.show()

