# -*- coding: utf-8 -*-
"""studentperformance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v5xmHy37VW4l72b8a97-ZURzRvcvFY1G
"""

import os

os.environ["KAGGLE_USERNAME"] = "kayalmass"
os.environ["KAGGLE_KEY"] = "0a056c2af71cce7989103f6e9b7948e9"

!pip install kaggle

!kaggle datasets download -d nikhil7280/student-performance-multiple-linear-regression

!unzip -o student-performance-multiple-linear-regression.zip -d student_data

import pandas as pd

df = pd.read_csv("student_data/Student_Performance.csv")
df.head()

print(df.shape)

print(df.columns)

df.info()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Extracurricular Activities'] = le.fit_transform(
    df['Extracurricular Activities']
)

X = df.drop('Performance Index', axis=1)
y = df['Performance Index']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.linear_model import LinearRegression

lr_model = LinearRegression()

lr_model.fit(X_train, y_train)

y_pred = lr_model.predict(X_test)

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

print("MSE :", mean_squared_error(y_test, y_pred))
print("MAE :", mean_absolute_error(y_test, y_pred))
print("R2 Score :", r2_score(y_test, y_pred))

result = pd.DataFrame({
    'Actual': y_test.values,
    'Predicted': y_pred
})

print(result.head(10))

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.scatter(y_test, y_pred)
plt.xlabel("Actual Performance Index")
plt.ylabel("Predicted Performance Index")
plt.title("Linear Regression Results")
plt.show()

print(df.isnull().sum())

print(df.duplicated().sum())

df_encoded = df.copy()

from sklearn.preprocessing import LabelEncoder
df_encoded['Extracurricular Activities'] = LabelEncoder().fit_transform(
    df_encoded['Extracurricular Activities']
)

print(df_encoded.corr())

print(df.columns)

df = df.drop('Extracurricular Activities', axis=1)

print(df.columns)

from sklearn.svm import SVR

svm_model = SVR(
    kernel='rbf',
    C=100,
    gamma='scale',
    epsilon=0.1
)

svm_model.fit(X_train, y_train)

y_pred = svm_model.predict(X_test)

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

print("MSE :", mean_squared_error(y_test, y_pred))
print("MAE :", mean_absolute_error(y_test, y_pred))
print("R2 Score :", r2_score(y_test, y_pred))

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.scatter(y_test, y_pred)
plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.title("SVM Regression")
plt.show()

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import matplotlib.pyplot as plt

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

metrics = ['MAE', 'MSE', 'R2 Score']
values = [mae, mse, r2]

plt.figure(figsize=(6,4))
plt.bar(metrics, values)
plt.title('SVM Performance Metrics')
plt.ylabel('Value')
plt.show()